import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DoubleHeader } from "@/src/components/DoubleHeader/navbar";
import React from 'react';
import { MantineProvider,ColorSchemeScript, mantineHtmlProps } from '@mantine/core';
import '@mantine/core/styles.css';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Memora單字記憶",
  description: "Generated by create next app",
  icons: {
    icon: "/memora-logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <DoubleHeader />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
